---
kind: Namespace
apiVersion: v1
metadata:
  name: development
  labels:
    compliance: open
    environment: development
---
apiVersion: v1
kind: Pod
metadata:
  name: sdkserver
  namespace: development
  labels:
    app: sdkserver
spec:
  containers:
  - name: sdkserver
    image: alpine:latest
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do wget -O- -T3 http://webserver; sleep 3; done;" ]
    resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-webserver
  namespace: development
spec:
  selector:
    matchLabels:
      app: webserver
      security: strict
  replicas: 2
  template:
    metadata:
      labels:
        app: webserver
        security: strict
    spec:
      containers:
      - name: webserver
        image: regisftm/webserver:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: development
  labels:
    service: webserver
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: webserver