apiVersion: v1
kind: Service
metadata:
  labels:
    service: mysql
  name: mysql
  namespace: robotshop
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    service: mysql
